/**
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Payload to patch a document. Only the fields you set are updated; omit a field to leave it unchanged.
*/
export class DocumentUpdateRequest {
    /**
    * New filename, including extension. 1–256 characters. Display only — it does not move the stored object nor re-trigger ingestion. Omit to keep the current filename.
    */
    'filename'?: string;
    /**
    * New creation date of the **source** document (ISO-8601, UTC). Describes the original file, not the platform row — `createdAt` is not affected. Omit to keep the current value.
    */
    'docCreate'?: Date;
    /**
    * New last-modified date of the **source** document (ISO-8601, UTC). Describes the original file, not the platform row — `updatedAt` is not affected. Omit to keep the current value.
    */
    'docUpdate'?: Date;
    /**
    * New JSON metadata. When provided, **replaces** the existing metadata map; omit to keep it unchanged.
    */
    'metadata'?: { [key: string]: any | null; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string"
        },
        {
            "name": "docCreate",
            "baseName": "docCreate",
            "type": "Date"
        },
        {
            "name": "docUpdate",
            "baseName": "docUpdate",
            "type": "Date"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any | null; }"
        }    ];

    static getAttributeTypeMap() {
        return DocumentUpdateRequest.attributeTypeMap;
    }
}

