/**
 * Verbatim AI — GenAI Backend API
 * Backend API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform.  ## Concepts  - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication  Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## Conventions  - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Body of POST /v1/doc/init. Declares a document and requests a presigned PUT URL for direct-to-storage upload.
*/
export class DocumentInitRequest {
    /**
    * ID of the corpus the document will be ingested into.
    */
    'corpusId': string;
    /**
    * Original filename, including extension.
    */
    'filename': string;
    /**
    * MIME content type the client will PUT. Must be in the platform-supported list (see GET /v1/doc/accept). The client MUST send the exact same value in the PUT `Content-Type` header.
    */
    'contentType': string;
    /**
    * ISO-639 language code used by the LLM during summarization. Defaults to `en`.
    */
    'lang'?: string;
    /**
    * Free-form label identifying the source of the document.
    */
    'provider'?: string;
    /**
    * Identifier of the user uploading the document. When the caller\'s JWT carries a `userId` claim, the value MUST match it — uploads on behalf of a different user are rejected with 403. May be omitted; in that case the JWT\'s `userId` is used when present.
    */
    'userId'?: string;
    /**
    * Original creation date of the source document (ISO-8601, UTC).
    */
    'docCreate'?: Date;
    /**
    * Original last-modified date of the source document (ISO-8601, UTC).
    */
    'docUpdate'?: Date;
    /**
    * Arbitrary key/value metadata attached to the document. Stored as JSONB.
    */
    'metadata'?: { [key: string]: any | null; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "corpusId",
            "baseName": "corpusId",
            "type": "string"
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "string"
        },
        {
            "name": "lang",
            "baseName": "lang",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "docCreate",
            "baseName": "docCreate",
            "type": "Date"
        },
        {
            "name": "docUpdate",
            "baseName": "docUpdate",
            "type": "Date"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any | null; }"
        }    ];

    static getAttributeTypeMap() {
        return DocumentInitRequest.attributeTypeMap;
    }
}

